#!/bin/sh

curl 'https://ghcr.io/token?scope=repository%3Asigstore%2Fcosign%2Fcosign%3Apull&service=ghcr.io'
curl 'https://auth.docker.io/token?scope=repository%3Alibrary%2Falpine%3Apull&service=registry.docker.io'
